### ISSUE TITLE
Warnings in console log for required properties?

### ISSUE THREAD

**Issue by aaronksaunders** [Kureev/react-native-navbar#24]
```
Warning: Failed propType: Required prop `navbar` was not specified in `NavigationBar`. Check the render method of `ReactParseExample`.
Warning: Failed propType: Required prop `route` was not specified in `NavigationBar`. Check the render method of `ReactParseExample`.
```

Don't see how they make sense for the initial route based on the information provided in the documentation

**Comment by chirag04** [comment]
+1

**Comment by Kureev** [comment]
Can you provide some code which cause this warning?

**Comment by aaronksaunders** [comment]
```javascript
    return (
        <Navigator
            ref="nav"
            style={styles.container}
            renderScene={this.renderScene}
            configureScene={(route) => {
                if (route.sceneConfig) {
                    return route.sceneConfig;
                }
                return Navigator.SceneConfigs.FloatFromRight;
            }}
            initialRoute={{
                component: SessionList,
                rightButtonTitle: 'New Session',
                navigationBar: <NavigationBar
                    onNext = {() => this.addNewSession()}
                    nextTitle = "Create Session"
                    title ='Tutor Manager' />
            }} />
    );
```

**Comment by Kureev** [comment]
"Required prop `navbar` was not specified" - super confusing, I'm not using this property at all.

**Comment by chirag04** [comment]
@Kureev  https://github.com/Kureev/react-native-navbar/blob/master/index.js#L61-L63

navbar is in the propType. I think it should not be there.

**Comment by chirag04** [comment]
@Kureev Can you check this?

**Comment by Kureev** [comment]
@chirag04 Yep, haven't time today, will take a look now

**Comment by Kureev** [comment]
Solved in 0.4.8

**Comment by gasperz** [comment]
This is still a problem. Also code that @chirag04 mentioned is still in repo.

**Comment by chirag04** [comment]
@gasperz  This is solved. Make sure you pass in navigator and route as props to navbar component.

@Kureev  I think you should document this(if missing).

**Comment by gasperz** [comment]
Sadly I still don't understand. Based on examples what would I need to do to get them working without warnings? 
Thanks for your effort.

**Comment by Kureev** [comment]
I'll try to take a look today. I thought that examples doesn't have any warnings now, but it seems I need to doublecheck.

**Comment by alvaromb** [comment]
I can confirm that the examples have this warning. This is because the required props ``navigator`` and ``route`` are not provided when declaring the navigation bar in the JSX code, but they are supplied in the ``renderScene`` method making everything work.

You can remove those warnings setting both props with an empty object, but I think that's not the best way to handle the issue. Maybe those props should not be required in the JSX tag but right now I can't clearly see how we could avoid the warning and specify that both props are needed internally.

**Comment by piyushchauhan2011** [comment]
:+1:  Thanks :smile:
