### ISSUE TITLE
Errors with 0.7.1 release.

### ISSUE THREAD

**Issue by piyushchauhan2011** [Kureev/react-native-navbar#55]
```
Unable to resolve module NavigatorNavigationBarStyles from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-navbar/index.js
Unable to resolve module StaticContainer.react from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-navbar/index.js
Unable to resolve module NavigatorNavigationBarStyles from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-navbar/index.js
Unable to resolve module StaticContainer.react from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-navbar/index.js
```

Did a fresh new project with react-native-cli and tried integrating the react-native-navbar. It gives me above error.

## AND

![screen shot 2015-07-16 at 5 33 25 pm](https://cloud.githubusercontent.com/assets/693487/8717667/d7e354ca-2be0-11e5-9173-1cc2be1f4cd8.png)

**Comment by Kureev** [comment]
`NavigatorNavigationBarStyles` and `StaticContainer.react` are deprecated in 0.7.x+, we need to replace them with analogs in latest versions

**Comment by piyushchauhan2011** [comment]
Yep :+1:

**Comment by Kureev** [comment]
@piyushchauhan2011 should be solved in `v0.6.1` ;) Check it out.

**Comment by piyushchauhan2011** [comment]
Still getting some error.

![screen shot 2015-07-16 at 6 16 37 pm](https://cloud.githubusercontent.com/assets/693487/8718314/df78569e-2be6-11e5-875f-be3b247dc882.png)

```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var NavigationBar = require('react-native-navbar');

var InitialView = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
});

var HelloTest = React.createClass({

  renderScene: function(route, navigator) {
    var Component = route.component;
    var navBar = route.navigationBar;

    if(navBar) {
      navBar = React.addons.cloneWithProps(navBar, {
        navigator: navigator,
        route: route
      });
    }

    return (
      <View style={styles.navigator}>
        {navBar}
        <Component navigator={navigator} route={route}/>
      </View>
    );
  },

  render: function() {
    return (
      <Navigator
        renderScene={this.renderScene}
        initialRoute={{
          component: InitialView,
          navigationBar: <NavigationBar title="Initial View" style={styles.navigator}/>
        }}
      />
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  navigator: {
    flex: 1,
  }
});

AppRegistry.registerComponent('HelloTest', () => HelloTest);
```

**Comment by piyushchauhan2011** [comment]
![screen shot 2015-07-16 at 6 23 51 pm](https://cloud.githubusercontent.com/assets/693487/8718454/e031e414-2be7-11e5-9936-49647199c658.png)

**Comment by Kureev** [comment]
Super informative stack trace :smile:

**Comment by piyushchauhan2011** [comment]
:smile:

**Comment by piyushchauhan2011** [comment]
Forgot the `Navigator` while destructuring.

**Comment by Kureev** [comment]
Perfect, so everything works fine now?

**Comment by piyushchauhan2011** [comment]
Yep
